loomio_show_poll_response = {
    "discussions": [],
    "events": [
        {
            "id": 8829416,
            "sequence_id": None,
            "position": 0,
            "depth": 0,
            "child_count": 0,
            "descendant_count": 0,
            "kind": "poll_created",
            "discussion_id": None,
            "created_at": "2021-09-28T18:47:59.834Z",
            "eventable_id": 234203,
            "eventable_type": "Poll",
            "pinned": True,
            "pinned_title": None,
            "parent_id": None,
            "actor_id": 4759171,
            "position_key": None,
            "recipient_message": None,
            "eventable": {"type": "poll", "id": 234203},
        }
    ],
    "users": [
        {
            "id": 4759171,
            "name": "policykit.org",
            "email": None,
            "username": None,
            "avatar_initials": "P",
            "avatar_kind": "initials",
            "thumb_url": None,
            "time_zone": "UTC",
            "locale": "en",
            "created_at": "2021-07-01T19:37:37.077Z",
            "titles": {},
            "email_verified": False,
            "bot": True,
        }
    ],
    "polls": [
        {
            "id": 234203,
            "attachments": [],
            "link_previews": [],
            "author_id": 4759171,
            "anyone_can_participate": False,
            "anonymous": False,
            "can_respond_maybe": None,
            "closed_at": "2021-09-28T18:50:14.603Z",
            "closing_at": "2021-10-01T00:00:00.000Z",
            "created_at": "2021-09-28T18:47:59.776Z",
            "content_locale": "en",
            "cast_stances_pct": 50,
            "custom_fields": {},
            "decided_voters_count": 1,
            "details": "Submitted on Open Collective: https://opencollective.com/metagov/expenses/51344",
            "details_format": "md",
            "discarded_at": None,
            "discarded_by": None,
            "discussion_id": None,
            "group_id": 710495,
            "hide_results_until_closed": False,
            "key": "m20ZprvH",
            "allow_long_reason": False,
            "multiple_choice": False,
            "notify_on_closing_soon": "nobody",
            "poll_type": "proposal",
            "poll_option_names": ["disagree", "agree"],
            "mentioned_usernames": [],
            "material_icon": "mdi-thumbs-up-down",
            "shuffle_options": False,
            "stance_counts": [1, 0],
            "total_score": 1,
            "stances_in_discussion": True,
            "specified_voters_only": False,
            "secret_token": "301e076e-3a3a-4b26-8735-8c1ebdc9ae7d",
            "title": "Expense 'test'",
            "undecided_voters_count": 1,
            "voter_can_add_options": False,
            "voters_count": 2,
            "versions_count": 2,
            "created_event_id": 8829416,
            "current_outcome_id": None,
            "my_stance_id": 4097752,
            "poll_option_ids": [940810, 940809],
            "tag_ids": [],
        }
    ],
    "groups": [
        {
            "id": 710495,
            "key": "ZrSTqeyG",
            "handle": "metagov",
            "name": "Metagovernance Project",
            "full_name": "Metagovernance Project",
            "content_locale": "un",
            "description": "",
            "description_format": "html",
            "logo_url": "/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1hSQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de7a024d4a7fa2c71ab2a4a6018a2aec355883cd/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MWm05eWJXRjBTU0lJY0c1bkJqb0dSVlE2RkhKbGMybDZaVjkwYjE5c2FXMXBkRnNIYVFJQUFta0NBQUk2Q25OaGRtVnlld2M2REhGMVlXeHBkSGxwVlRvS2MzUnlhWEJVIiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--1169be3c3fd7d3cdf1b6a05657df457bb826f164/metagov.png%3F1609863130",
            "created_at": "2021-01-05T16:10:21.149Z",
            "creator_id": 879750,
            "members_can_add_members": True,
            "members_can_add_guests": True,
            "members_can_announce": True,
            "members_can_create_subgroups": True,
            "members_can_start_discussions": True,
            "members_can_edit_discussions": True,
            "members_can_edit_comments": True,
            "members_can_delete_comments": True,
            "members_can_raise_motions": True,
            "admins_can_edit_user_content": False,
            "polls_count": 119,
            "closed_polls_count": 78,
            "discussions_count": 2,
            "public_discussions_count": 2,
            "group_privacy": "open",
            "memberships_count": 3,
            "pending_memberships_count": 0,
            "accepted_memberships_count": 3,
            "membership_granted_upon": "approval",
            "discussion_privacy_options": "public_only",
            "admin_memberships_count": 3,
            "archived_at": None,
            "attachments": [],
            "link_previews": [],
            "new_threads_max_depth": 2,
            "new_threads_newest_first": False,
            "cover_url": None,
            "experiences": {},
            "enable_experiments": False,
            "features": {},
            "open_discussions_count": 2,
            "closed_discussions_count": 0,
            "recent_activity_count": 0,
            "is_visible_to_public": True,
            "is_subgroup_of_hidden_parent": False,
            "is_visible_to_parent_members": False,
            "parent_members_can_see_discussions": True,
            "org_memberships_count": 3,
            "org_discussions_count": 2,
            "org_members_count": 3,
            "subscription": {"max_members": None, "max_threads": None, "active": True, "members_count": None},
            "subgroups_count": 1,
            "new_host": None,
            "complete": True,
            "parent_id": None,
            "current_user_membership_id": None,
            "tag_ids": [],
        }
    ],
    "parent_groups": [],
    "memberships": [],
    "tags": [],
    "outcomes": [],
    "stances": [
        {
            "id": 4097752,
            "reason": "",
            "reason_format": "html",
            "content_locale": "un",
            "latest": True,
            "admin": True,
            "cast_at": None,
            "created_at": "2021-09-28T18:47:59.820Z",
            "locale": "en",
            "versions_count": 1,
            "attachments": [],
            "link_previews": [],
            "volume": "normal",
            "inviter_id": None,
            "poll_id": 234203,
            "participant_id": 4759171,
            "revoked_at": None,
            "order_at": "2021-09-28T18:47:59.820Z",
            "option_scores": {},
            "my_stance": True,
        }
    ],
    "poll_options": [
        {
            "name": "disagree",
            "id": 940810,
            "poll_id": 234203,
            "priority": 1,
            "voter_scores": {},
            "color": "#F6A82B",
            "total_score": 0,
        },
        {
            "name": "agree",
            "id": 940809,
            "poll_id": 234203,
            "priority": 0,
            "voter_scores": {"879750": 1},
            "color": "#00D177",
            "total_score": 1,
        },
    ],
    "parent_events": [],
    "polls": [
        {
            "id": 234203,
            "attachments": [],
            "link_previews": [],
            "author_id": 4759171,
            "anyone_can_participate": False,
            "anonymous": False,
            "can_respond_maybe": None,
            "closed_at": "2021-09-28T18:50:14.603Z",
            "closing_at": "2021-10-01T00:00:00.000Z",
            "created_at": "2021-09-28T18:47:59.776Z",
            "content_locale": "en",
            "cast_stances_pct": 50,
            "custom_fields": {},
            "decided_voters_count": 1,
            "details": "Submitted on Open Collective: https://opencollective.com/metagov/expenses/51344",
            "details_format": "md",
            "discarded_at": None,
            "discarded_by": None,
            "discussion_id": None,
            "group_id": 710495,
            "hide_results_until_closed": False,
            "key": "m20ZprvH",
            "allow_long_reason": False,
            "multiple_choice": False,
            "notify_on_closing_soon": "nobody",
            "poll_type": "proposal",
            "poll_option_names": ["disagree", "agree"],
            "mentioned_usernames": [],
            "material_icon": "mdi-thumbs-up-down",
            "shuffle_options": False,
            "stance_counts": [1, 0],
            "total_score": 1,
            "stances_in_discussion": True,
            "specified_voters_only": False,
            "secret_token": "301e076e-3a3a-4b26-8735-8c1ebdc9ae7d",
            "title": "Expense 'test'",
            "undecided_voters_count": 1,
            "voter_can_add_options": False,
            "voters_count": 2,
            "versions_count": 2,
            "created_event_id": 8829416,
            "current_outcome_id": None,
            "my_stance_id": 4097752,
            "poll_option_ids": [940810, 940809],
            "tag_ids": [],
        }
    ],
    "meta": {"root": "polls", "total": None},
}
