# Generated by Django 3.2.2 on 2021-05-31 18:18

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_auto_20210506_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slack',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.plugin',),
        ),
    ]
