# Generated by Django 3.2.2 on 2021-06-22 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('metagov_slack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackVote',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.governanceprocess',),
        ),
    ]
