# Generated by Django 3.2.2 on 2021-06-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('metagov_slack', '0002_slackvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlackVote',
        ),
        migrations.CreateModel(
            name='SlackEmojiVote',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.governanceprocess',),
        ),
    ]
