# Generated by Django 3.2.2 on 2021-12-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_auto_20211101_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discord',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.plugin',),
        ),
    ]
