# Generated by Django 3.2.2 on 2021-12-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211101_2053'),
        ('metagov_discord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordVote',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.governanceprocess',),
        ),
    ]
