# Generated by Django 3.2.2 on 2021-12-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_governanceprocess_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendGrid',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.plugin',),
        ),
    ]
