# Generated by Django 3.1.5 on 2021-02-12 18:53

from django.db import migrations, models
import metagov.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, validators=[metagov.core.models.validate_process_name])),
                ('callback_url', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('created', 'CREATED'), ('pending', 'PENDING'), ('completed', 'COMPLETED')], default='created', max_length=15)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=dict)),
                ('outcome', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
