# Generated by Django 3.2.2 on 2021-07-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governanceprocess',
            name='callback_url',
            field=models.CharField(blank=True, help_text='Callback URL to notify when the process is updated', max_length=100, null=True),
        ),
    ]
