# Generated by Django 3.1.5 on 2021-03-22 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asyncprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncprocess',
            name='errors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='asyncprocess',
            name='outcome',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='asyncprocess',
            name='data',
            field=models.OneToOneField(help_text='Datastore to persist any data', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.datastore'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='data',
            field=models.OneToOneField(help_text='Datastore to persist any data', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.datastore'),
        ),
    ]
