# Generated by Django 3.1.8 on 2021-04-21 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210329_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governanceprocess',
            name='data',
        ),
        migrations.AlterField(
            model_name='governanceprocess',
            name='state',
            field=models.OneToOneField(help_text='Datastore to persist any internal state', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.datastore'),
        ),
    ]
