# Generated by Django 3.2.2 on 2021-07-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_governanceprocess_callback_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='readable_name',
            field=models.CharField(blank=True, help_text='Human-readable name for the community', max_length=100),
        ),
    ]
