# Generated by Django 3.1.5 on 2021-03-22 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210322_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncprocess',
            name='state',
            field=models.OneToOneField(help_text='Datastore to persist any data', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.datastore'),
        ),
        migrations.AlterField(
            model_name='asyncprocess',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
