# Generated by Django 3.2.2 on 2021-11-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210913_1744'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='linkedaccount',
            name='unique_identifer_on_community_platform',
        ),
    ]
