# Generated by Django 3.1.5 on 2021-03-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210322_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncprocess',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Data to serialize and send back to driver'),
        ),
    ]
