# Generated by Django 3.2.2 on 2021-11-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_linkedaccount_unique_identifer_on_community_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='community_platform_id',
            field=models.CharField(blank=True, help_text='Optional identifier for this instance. If multiple instances are allowed per community, this field must be set to a unique value for each instance.', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='plugin',
            unique_together={('name', 'community', 'community_platform_id')},
        ),
    ]
